FROM maxkondr/porta-os

LABEL maintainer="PortaOne Inc."
LABEL summary="Image for CPE profile dispatcher"

ARG PORTA_GIT_COMMIT=unspecified
ARG PORTA_GIT_TAG=unspecified
ARG PORTA_GIT_BRANCH=master
ARG PORTA_APP_NAME='ba-cpe-profile-dispatcher'

ENV PORTA_GIT_TAG=$PORTA_GIT_TAG
ENV PORTA_GIT_COMMIT=$PORTA_GIT_COMMIT
ENV PORTA_APP_NAME=$PORTA_APP_NAME

LABEL PORTA_GIT_TAG=$PORTA_GIT_TAG
LABEL PORTA_GIT_COMMIT=$PORTA_GIT_COMMIT
LABEL PORTA_GIT_BRANCH=$PORTA_GIT_BRANCH

RUN mkdir -p /app
RUN mkdir -p /etc/porta
ADD $PORTA_APP_NAME /app/$PORTA_APP_NAME
EXPOSE 7780
ENTRYPOINT ["/app/$PORTA_APP_NAME"]
